# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 107efd69408e926d6c7b01210b331c1a7ee1191cce1a0de3c392689493c4eb38c6985a5ad839d8a931387bddd897b7a92d6c6c8fe3ede5fd4fac1848e979135d

test:
  secret_key_base: 042a03de0caf9a334a469fb29e30d118c105e6e2d341e39e43cb74bd6b1ee29856f628f44a20e6c7b53226e43cfcf09bd0ae3597b9a56f0eff4be4437804029f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
